name: kira_qr_transfer
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "^2.5.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  archive: ^3.3.0
  barcode_image: ^2.0.0
  image: ^3.1.3
  crypto: ^3.0.1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: